In [1]:
# ml class 1

In [1]:
import numpy as np

In [66]:
a=np.random.randint(0,9,(5,5))
b=np.random.randint(0,9,(5,5))
c=np.ones((5,5),'int')

In [67]:
a

array([[3, 3, 0, 3, 0],
       [6, 4, 6, 8, 5],
       [4, 7, 8, 4, 4],
       [6, 8, 4, 1, 8],
       [8, 8, 3, 3, 6]])

In [68]:
b

array([[5, 0, 5, 1, 4],
       [2, 3, 5, 6, 7],
       [7, 3, 2, 3, 8],
       [3, 5, 8, 5, 1],
       [3, 2, 1, 2, 3]])

In [69]:
c=np.ones((5,5),'int')
for i in range(0,5):
    for j in range(0,5):
        for k in range(0,5):
            c[i][j] += a[i][k]*b[k][j]

In [70]:
c

array([[ 31,  25,  55,  37,  37],
       [120,  81, 132,  99, 124],
       [115,  74, 108,  99, 146],
       [102,  58,  95,  88, 138],
       [105,  61, 117,  93, 134]])

In [71]:
z=np.multiply(a,b)
z

array([[15,  0,  0,  3,  0],
       [12, 12, 30, 48, 35],
       [28, 21, 16, 12, 32],
       [18, 40, 32,  5,  8],
       [24, 16,  3,  6, 18]])

In [10]:
import statistics as st
# mean
m=np.mean(a)
m

3.68

In [11]:
mod=np.median(a)
mod

4.0

In [12]:
mo=st.mode(a)

TypeError: unhashable type: 'numpy.ndarray'

In [23]:
a

array([[8, 2, 7, 6, 6],
       [4, 2, 5, 6, 3],
       [0, 2, 4, 3, 0],
       [0, 2, 1, 2, 1],
       [0, 5, 2, 1, 1]])

In [24]:
a = a.reshape((1,-1))
a

array([[8, 2, 7, 6, 6, 4, 2, 5, 6, 3, 0, 2, 4, 3, 0, 0, 2, 1, 2, 1, 0, 5,
        2, 1, 1]])

In [13]:
st.mode(a)

TypeError: unhashable type: 'numpy.ndarray'

In [16]:
a = a.flatten('C')

In [17]:
a

array([0, 0, 0, 5, 2, 7, 4, 6, 2, 1, 1, 7, 7, 4, 3, 4, 4, 8, 6, 6, 1, 0,
       6, 7, 1])

In [18]:
st.mode(a)

0

In [19]:
import matplotlib.pyplot as plt

In [20]:
plt.boxplot(a)

{'whiskers': [<matplotlib.lines.Line2D at 0x20bf7c82c70>,
 'caps': [<matplotlib.lines.Line2D at 0x20bf7c76250>,
 'boxes': [<matplotlib.lines.Line2D at 0x20bf7c829a0>],
 'medians': [<matplotlib.lines.Line2D at 0x20bf7c767f0>],
 'fliers': [<matplotlib.lines.Line2D at 0x20bf7c76ac0>],
 'means': []}

In [30]:
a = np.insert(a,0,20)

In [31]:
plt.boxplot(a)

{'whiskers': [<matplotlib.lines.Line2D at 0x20bf77db160>,
 'caps': [<matplotlib.lines.Line2D at 0x20bf77db700>,
 'boxes': [<matplotlib.lines.Line2D at 0x20bf77dae50>],
 'medians': [<matplotlib.lines.Line2D at 0x20bf77dbca0>],
 'fliers': [<matplotlib.lines.Line2D at 0x20bf77dbfa0>],
 'means': []}

In [32]:
a

array([ 20, 120, 100,   0,   0,   0,   5,   2,   7,   4,   6,   2,   1,
         1,   7,   7,   4,   3,   4,   4,   8,   6,   6,   1,   0,   6,
         7,   1])

In [33]:
bt=np.transpose(c)
bt

array([[ 52, 110,  17, 113,  40],
       [ 52, 110,  17, 113,  40],
       [ 52, 110,  17, 113,  40],
       [ 52, 110,  17, 113,  40],
       [ 52, 110,  17, 113,  40]])

In [34]:
c

array([[ 52,  52,  52,  52,  52],
       [110, 110, 110, 110, 110],
       [ 17,  17,  17,  17,  17],
       [113, 113, 113, 113, 113],
       [ 40,  40,  40,  40,  40]])

In [ ]:
bi=np.inv

In [2]:
# c1 homework

In [2]:
import pandas as pd

In [10]:
# using dictionary
data = {
    'names':['ajay','binod','chada','dholu'],
    'age':[23,24,19,21],
    'address':['abc','def','ghi','sdf']
}

In [11]:
df=pd.DataFrame(data)

In [12]:
df

names  age address
0   ajay   23     abc
1  binod   24     def
2  chada   19     ghi
3  dholu   21     sdf

In [19]:
data2=[['ajay',23,'sff'],['binod',24,'sdf'],['chada',21,'def'],['dholu',19,'uee']]
df2=pd.DataFrame(data2,columns=['name','age','address'])
df2

name  age address
0   ajay   23     sff
1  binod   24     sdf
2  chada   21     def
3  dholu   19     uee

In [3]:
df3= pd.DataFrame(columns=['id','name','age'])

In [4]:
df.loc(0)=[1,'ajay',22]

SyntaxError: cannot assign to function call (309927788.py, line 1)

In [ ]:
pip in